package codegen

import (
	"fmt"
	"strings"
)

// ファイルの最上部に出力
const header = "// Code generated by %s DO NOT EDIT."

func formatHeader(name string) string {
	return fmt.Sprintf(header, name)
}

// パッケージ名を出力
const packageCode = "package %s"

func formatPackage(name string) string {
	return fmt.Sprintf(packageCode, name)
}

// チェックサムを出力
const checkSumCode = `const CheckSum = "%s"`

func formatCheckSum(checkSum string) string {
	return fmt.Sprintf(checkSumCode, checkSum)
}

// extends 未指定の場合の MetaData の型
const defaultMetaDataCode = `
type ConstantMetaData[T comparable] struct {
	ID   T      ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
}

`

// extends_defs 定義時の props の型定義出力
const extendsDefMetaDataPropsTypeCode = `
type %sMetaDataProps struct {
	Name   string ` + "`json:\"name\"`" + `
	%s
}
`

func formatExtendsDefMetaDataPropsType(tName string, params string) string {
	return fmt.Sprintf(extendsDefMetaDataPropsTypeCode, tName, params)
}

// extends_defs 定義時の MetaData の型定義出力
const extendsDefMetaDataTypeCode = `
type %sMetaData[T %s] struct {
	ID T
	*%sMetaDataProps
}
`

func formatExtendsDefMetaDataType(name string) string {
	return fmt.Sprintf(extendsDefMetaDataTypeCode, name, name, name)
}

// extends_defs 定義時の interface の型定義出力
const extendsDefInterfaceTypeCode = `
type %s interface {
	Props() (*%sMetaDataProps, bool)
}
`

func formatExtendsDefInterfaceType(name string) string {
	return fmt.Sprintf(extendsDefInterfaceTypeCode, name, name)
}

// extends が extends_defs を参照しているときの MetaData の型
const constantMetaDataTypeByExtendsDefCode = `
type %sMetaData %sMetaData[%s]
`

func formatConstantMetaDataTypeByExtendsDef(name string, templateName string) string {
	return fmt.Sprintf(constantMetaDataTypeByExtendsDefCode, name, templateName, name)
}

// コメントの出力
const constantCommentCode = "// %s ... %s"

func formatConstantComment(name, comment string) string {
	return fmt.Sprintf(constantCommentCode, name, comment)
}

// 型定義の出力
const constantTypeCode = `
type %s %s

`

func formatConstantType(name, base string) string {
	return fmt.Sprintf(constantTypeCode, name, base)
}

// String メソッド
const constantMethodStringCode = `
func (c %s) String() string {
	return string(c)
}

`

func formatConstantMethodString(name string) string {
	return fmt.Sprintf(constantMethodStringCode, name)
}

// Meta メソッド
const constantMethodMetaCode = `
func (c %s) Meta() (*%s, bool) {
	m, ok := %s[c]
	return m, ok
}

`

func formatConstantMethodMeta(name string) string {
	tName := formatConstantMetaDataTypeName(name)
	mapName := formatConstantMetaDataMapVariableName(name)
	return fmt.Sprintf(constantMethodMetaCode, name, tName, mapName)
}

// Name メソッド
const constantMethodNameCode = `
func (c %s) Name() string {
	if m, ok := c.Meta(); ok {
		return m.Name
	}
	return ""
}

`

func formatConstantMethodName(name string) string {
	return fmt.Sprintf(constantMethodNameCode, name)
}

// 実際の定数の出力
const constantValuesCode = `
const (
%s
)

`

func formatConstantValues(values string) string {
	return fmt.Sprintf(constantValuesCode, values)
}

// 定数の値定義部分の出力
const constantValueCode = `%s%s %s = %s`

func formatConstantValue(tName, vName string, hasDoubleQuote bool, value string) string {
	outputValue := value
	if hasDoubleQuote {
		outputValue = fmt.Sprintf(`"%s"`, value)
	}
	return fmt.Sprintf(constantValueCode, tName, vName, tName, outputValue)
}

// MetaData の型名
const constantMetaDataTypeNameCode = `%sMetaData`

func formatConstantMetaDataTypeName(tName string) string {
	return fmt.Sprintf(constantMetaDataTypeNameCode, tName)
}

// extends 未指定の場合の generics での MetaData の型定義
const constantMetaDataTypeByGenericsCode = `
type %s ConstantMetaData[%s]

`

func formatConstantMetaDataByGenerics(tName string) string {
	return fmt.Sprintf(constantMetaDataTypeByGenericsCode, formatConstantMetaDataTypeName(tName), tName)
}

// extends 指定時の MetaData の型定義
const constantMetaDataTypeCode = `
type %s struct {
%s
}

`

func formatConstantMetaDataType(tName, params string) string {
	return fmt.Sprintf(constantMetaDataTypeCode, formatConstantMetaDataTypeName(tName), params)
}

// MetaData のパラメータ部分の型定義
const constantMetaDataTypeCodeParam = `%s   %s ` + "`json:\"%s\"`"

func formatConstantMetaDataTypeParam(name, tName string) string {
	return fmt.Sprintf(constantMetaDataTypeCodeParam, toPascalCase(name), tName, name)
}

// MetaData の ID 部分の型定義
func formatConstantMetaDataTypeID(tName string) string {
	return fmt.Sprintf(constantMetaDataTypeCodeParam, "ID", tName, "id")
}

// MetaData のマップ変数名
const constantMetaDataMapVariableNameCode = `%sMap`

func formatConstantMetaDataMapVariableName(tName string) string {
	return fmt.Sprintf(constantMetaDataMapVariableNameCode, tName)
}

// MetaData のマップ型名
const constantMetaDataMapTypeCode = `map[%s]*%s`

func formatConstantMetaDataMapTypeName(tName string) string {
	return fmt.Sprintf(constantMetaDataMapTypeCode, tName, formatConstantMetaDataTypeName(tName))
}

// MetaData のマップ変数の出力
const constantMetaDataMapCode = `
var %s %s

`

func formatConstantMetaDataMap(tName string) string {
	return fmt.Sprintf(constantMetaDataMapCode, formatConstantMetaDataMapVariableName(tName), formatConstantMetaDataMapTypeName(tName))
}

// MetaData の slice の定義
const constantMetaDataListCode = `
var %s = []*%s{
%s
}

`

func formatConstantMetaDataList(tName, elements string) string {
	return fmt.Sprintf(constantMetaDataListCode, toPluralForm(tName), formatConstantMetaDataTypeName(tName), elements)
}

// MetaData の slice の1要素の出力
const constantMetaDataListElementCode = `{
%s
},`

func formatConstantMetaDataListElement(params string) string {
	return fmt.Sprintf(constantMetaDataListElementCode, params)
}

// MetaData のパラメータの出力
const constantMetaDataParamCode = `%s: %s,`

func formatConstantMetaDataParam(name, value string, hasDoubleQuote bool) string {
	if hasDoubleQuote {
		value = fmt.Sprintf(`"%s"`, value)
	}
	return fmt.Sprintf(constantMetaDataParamCode, toPascalCase(name), value)
}

// MetaData の slice の値の出力
const constantMetaDataSliceValueCode = `%s{%s}`

func formatConstantMetaDataSliceParam(name, typ string, values []string, hasDoubleQuote bool) string {
	if hasDoubleQuote {
		for i, v := range values {
			values[i] = fmt.Sprintf(`"%s"`, v)
		}
	}

	value := fmt.Sprintf(constantMetaDataSliceValueCode, typ, strings.Join(values, ","))
	return fmt.Sprintf(constantMetaDataParamCode, toPascalCase(name), value)
}

// Constants の型名
const constantsTypeNameCode = `Constants`

// Constants の変数名
const constantsVariableNameCode = `ConstantsData`

// Constants の型と値定義
const constantsStructCode = `
type ` + constantsTypeNameCode + ` struct {
%s
}

var ` + constantsVariableNameCode + ` *` + constantsTypeNameCode + `

`

func formatConstantsStruct(params string) string {
	return fmt.Sprintf(constantsStructCode, params)
}

// Constants のパラメータの出力
const constantsStructParamCode = `%s %s ` + "`json:\"%s\"`"

func formatConstantsStructParam(name, tName string) string {
	return fmt.Sprintf(constantsStructParamCode, toPascalCase(name), tName, name)
}

// GetConstIDs メソッド
const constantsMethodGetConstIDsCode = `
// deprecated use ConstIDs
func (c *` + constantsTypeNameCode + `) GetConstIDs() [][]any {
	%s
	return [][]any{
		%s
	}
}

func (c *` + constantsTypeNameCode + `) ConstIDs() [][]any {
	return c.GetConstIDs()
}

`

func formatConstantsMethodGetConstIDs(generateAnySliceCodes, constantsParams string) string {
	return fmt.Sprintf(constantsMethodGetConstIDsCode, generateAnySliceCodes, constantsParams)
}

// Constants の slice の中身を init 内で生成するコード
const generateAnySliceCode = `
%s := []any{}
for _, v := range c.%s {
	%s = append(%s, v.ID)
}
`

func formatGenerateAnySliceCode(name, tName string) string {
	return fmt.Sprintf(generateAnySliceCode, name, toPluralForm(tName), name, name)
}

// init 関数の出力
const initCode = `
func init() {
	%s
	` + constantsVariableNameCode + ` = &` + constantsTypeNameCode + `{
		%s
	}
}
`

func formatInitCode(generateMapCodes, constantsParams string) string {
	return fmt.Sprintf(initCode, generateMapCodes, constantsParams)
}

// init 内のmapの初期化
const generateMapCode = `
	%s = %s{}
	for _, v := range %s {
		%s[v.ID] = v
	}
`

func formatGenerateMapCode(tName string) string {
	return fmt.Sprintf(generateMapCode,
		formatConstantMetaDataMapVariableName(tName),
		formatConstantMetaDataMapTypeName(tName),
		toPluralForm(tName),
		formatConstantMetaDataMapVariableName(tName),
	)
}

// init 内の Constants のパラメータの出力
const constantsInitParamCode = `%s: %s,`

func formatConstantsInitParam(name, value string) string {
	return fmt.Sprintf(constantsInitParamCode, name, value)
}
